/* Decompose by Channel — index.js
 *
 * DecompositionPanel (decomposition-panel.js) owns the panel and its open/close
 * logic. The toolbar button is generated by PluginRegistry.buildToolbarButtons()
 * and wired to this module's activate() by bindToolbarButtons(); activate()
 * drives DecompositionPanel.toggle() directly (no DOM-click delegation), so the
 * tool works even when the button is created dynamically.
 */
PluginRegistry.implement('decompose-channels', {
  _ctx: null,

  init(ctx) {
    this._ctx = ctx;
    return this;
  },

  activate() {
    if (typeof DecompositionPanel === 'undefined' || !DecompositionPanel.toggle) {
      return { active: false };
    }
    return { active: DecompositionPanel.toggle() };
  },

  getState() {
    // DecompositionPanel manages its own state, nothing extra to persist
    return null;
  },

  dispose() {}
});
